### ISSUE TITLE
Can Nightshift have a customizable property list in target tab

### ISSUE THREAD

**Issue by astromiester1** [rrskybox/Nightshift#5]
For instance, can nightshift on the target tab display

Major Axis, Minor Axis and Altitude .

**Comment by rrskybox** [comment]
I think it would be pretty hard to set the target display grid user configurable.  In fact, I'm not even sure how to do that given the number of object parameters and formats.

I actually intended for Nightshift to be opened over TSX in the Star Chart area, next to a Find window.  That way when you tap on a target, both a reference image (from the web) and all the object parameters can be visible including major axis, minor axis and current altitude.  If you want, you can run the TSX clock forward to see what values like altitude are around the time that you want to shoot.  Otherwise, just use Image Planner which graphs that stuff for you.

![image](https://github.com/rrskybox/Nightshift/assets/40242027/2fa0dc5b-0750-4449-849a-fb8bc62f0822)

**Comment by astromiester1** [comment]
I already played with it last night. Your code that is...I just added the parameters I wanted pasting your code from target type and added the new string types. Then just added the new colms and order in VS Gui. If ya wanna see it or the upload let me know. Thanks Dale

**Comment by astromiester1** [comment]
![nightshift new](https://github.com/rrskybox/Nightshift/assets/14363854/67b3acd4-8b7f-46e9-bc19-56c24d6f607c)

Here is a snapshot....

**Comment by rrskybox** [comment]
You're absolutely right -- adding and/or replacing any one (or two or three) _specific_ target characteristics is straightforward, and it looks like you more than sorted out how to do it -- by direct code modification.  I guess that really wasn't my point.  What happens if someone else wants a different set of attributes listed?  Or, what happens if you decide you need to add yet another set of columns like Magnitude and Azimuth?  This is the _general_ case that that is much more complex, i.e.  how to enable a user to pick a unique combination of target attributes to suit their needs, then incorporate that selection into a set of columns within a limited screen.  In some sense, this is analogous the Excel problem, although there are only maybe 20 or 30 available target attributes, that's still more than I personally want to try to take on.   I think you already have the solution you need in hand -- fork a copy of Nightshift and modify to your needs as they arise.  The code is fairly modular so you can track any fixes in other modules as I might incorporate.  I actually only have one I can think of in the very near future which will minimally connect to ExoScan functionality to the Imaging and Log modules.

Just out of curiosity though, why do you want to compare major/minor axis attributes in the target grid.  I can guess why you might want to look at altitude, although for any long imaging sequence you would still need to know which direction it is headed over time.  I would think, however, that you would have already considered the target size attributes when you first selected the target.   It feels like you are trying to merge some of the functionality of Image Planner (which does show potential target size in grid format) into Nightshift.  Can you give me a sense of the context here?

**Comment by astromiester1** [comment]
Thanks for your comments and code Rick…  I wanted Major and Minor Axis which basically tells me the real size of the target in mm in X and Y dimensions. It helps me see if I have a match for my particular camera FOV to the target of interest.

I guess image planner would help with that too but its nice to see it in Nightshift since that’s what I do in TSX.

Maybe, another way for user configurability of target columns is for your targets query is just to pull what every query and attribute columns the user has inside TSX using observation list Whatsup.

Thanks
Dale

**Comment by astromiester1** [comment]
Hi Rick, can you tell me the easiest way to have the DataGridTextColumn object used in your code for the targets to sort correctly based on number representation.  Im trying to sort on Altitude for instance on the targets. The table is all strings and I thought maybe, you could set the table property to a number format , so it would sort correctly... No luck so far . Thougth this would be easy but having trouble.... Thanks Dale

[
![nightshift new2](https://github.com/rrskybox/Nightshift/assets/14363854/20f7e8cd-db2c-49a2-b7b0-58f5afd867a2)
](url)

**Comment by rrskybox** [comment]
To set the format of a datagrid column, use:

  TargetDataGrid.Columns[i].DefaultCellStyle.Format - "#";     //No decimals

Of course you'd have to parse the sexidecimal string into a decimal for it to work.  I would probably merely convert the sexidecimal string to a decimal string and leave the column format as a its original default, a string.  The conversion would be dead simple as for altitude, you don't need anything beyond the sign and one or two following characters.  Just do a Split on the degree character and discard the rest.

Anyway, those are the options that I can think of.  Please note that it is this sort of thing that makes the general case I talked about above very problematic, if not simply impractical.

On the Observing List suggestion, a problem is that WhatsUp configuration can't be read programmatically, unless it is exported to a text file.  If you did that, then you might as well use the Observing List functionality in TSX.  That said, one could load the targets into the clipboard, then input them into an Observing List and run WhatsUp, I suppose.  That might be useful.

**Comment by astromiester1** [comment]
Hi Rick, I couldnt get that to work, so I just ended up adding float variables for Altitude, Major and Minor axis in the targetspec class. 

How would one alter the search criteria for targets in nightshift. I noticed a distinct target list in your list... I think 24 targets...

![nightshift new3](https://github.com/rrskybox/Nightshift/assets/14363854/259ae36a-7da2-48f4-aaf5-0e60c7ee23b3)


Thanks
Dale

**Comment by astromiester1** [comment]
It appears that FormPreview.cs controls the number of targets... iWidthD and iHeightD. 30x20 ArcMins.. Is that correct?

**Comment by astromiester1** [comment]
Nope, thats not it... Its for the image previewer...

**Comment by astromiester1** [comment]
Ahh... I think it grabs the target list from the Humanson Plan list.. Hmmmm.. Can nightshift just bring in the targets from SKYX... I know you did something to make your own query pulls from SKYX I think using QuickPick, SuperScan, etc.. BTW, I started looking at VariScan details.. Its very complicated.. You truly are a smart fellow.... What is your background by the way? Astrophysics with code warrior combined or something close I guess... Thanks Dale

**Comment by rrskybox** [comment]
Yes, Nightshift pulls its target list from the list of target configuration (XML) files in the Humason folder.  Nightshift was written to provide an integrated dashboard and log reader for Image Planner, Humason and the three special purpose sequencers, SuperScan, VariScan and (recently) ExoScan.  Much like its architectural relationship with TSX, it was never intended to implement any of the functions already implemented in those applications, merely vector a user into them as desired.  That's probably why you don't see some of the functions you might have expected -- they're implemented elsewhere within a more "appropriate" companion app, at least IMHO.

To read a list from a TSX Object List query instead of Humason, one could replace the TargetPlans class definition with one that generated and read out the results of a query using the TSX DataWizard and ObjectInformation classes.  An example for this is found in the ImagePlanner ObjectList class (https://github.com/rrskybox/ImagePlanner/blob/master/ImagePlanner/ObjectList.cs).  Let me know if you'd like me to walk you through it.

I do have some background in writing data communications software, but the astro stuff is all acquired through continuing education as provided by a massive number of accumulated mistakes.
