### ISSUE TITLE
Made some changes to Nightshift you may want....

### ISSUE THREAD

**Issue by astromiester1** [rrskybox/Nightshift#6]
Hi Rick,  I can upload my changes to a google drive link if you like. Otherwise, let me know how to upload a build I did...

One thing I added was some different parameters to have in the target list as shown in picture provided enclosed...

Thanks
Dale

![nightshift mod dale d](https://github.com/rrskybox/Nightshift/assets/14363854/62c46f6a-ba48-4485-8a4a-efe66618c420)

**Comment by rrskybox** [comment]
The easiest thing to do is to attach just those modules that you've modified to a comment here in GitHub and I'll take a look at them.   The only downside I see is that the app footprint gets a whole lot larger to the point that it doesn't fit on a screen with much else. 

In general, I guess I'm coming from a different place anyway -- I view NightShift as merely a dashboard for managing the rest of the TSX Tools.   Image Planner seems to be the right place to look at and compare target opportunities.   Accordingly, what I'd like to do is see if I can't add this target spreadsheet view into Image Planner rather than NightShift.  I just think it makes more sense as part of that app.  It's not a bad idea to look at targets this way, I just think it's in the wrong place.  Thoughts?

By the way, I think I should be able to figure out this once I look at your code, but what is the "Altitude" field?  Is it the altitude at some specific time or the max altitude for the imaging period or altitude at transit, or something else?

**Comment by astromiester1** [comment]
Its the current altitude of target real time..That is once I hit refresh button...Yes, it might make more sense in ip. Would that replace prospect watsup or just add another tab?. I have 3 large screens so fov for apps doesnt matter to me...Sent via the Samsung Galaxy S22 5G, an AT&T 5G smartphone
-------- Original message --------From: Rick McAlister ***@***.***> Date: 5/9/24  9:58 PM  (GMT-05:00) To: rrskybox/Nightshift ***@***.***> Cc: astromiester1 ***@***.***>, Author ***@***.***> Subject: Re: [rrskybox/Nightshift] Made some changes to Nightshift you may want.... (Issue #6) 
The easiest thing to do is to attach just those modules that you've modified to a comment here in GitHub and I'll take a look at them.   The only downside I see is that the app footprint gets a whole lot larger to the point that it doesn't fit on a screen with much else.
In general, I guess I'm coming from a different place anyway -- I view NightShift as merely a dashboard for managing the rest of the TSX Tools.   Image Planner seems to be the right place to look at and compare target opportunities.   Accordingly, what I'd like to do is see if I can't add this target spreadsheet view into Image Planner rather than NightShift.  I just think it makes more sense as part of that app.  It's not a bad idea to look at targets this way, I just think it's in the wrong place.  Thoughts?
By the way, I think I should be able to figure out this once I look at your code, but what is the "Altitude" field?  Is it the altitude at some specific time or the max altitude for the imaging period or altitude at transit, or something else?

**Comment by rrskybox** [comment]
Three screens... wow, sounds like you might run Flight Simulator or such in your other spare time.  I run on everything from a 27 inch to a laptop (when I'm in the boonies with my portable system)  so I've got keep the the windows constrained.

I'm torn between adding a new button or augmenting WhatsUp, but leaning towards the latter.  Architecturally the latter is the cleanest (essentially an observing list query w/o TSX), but also somewhat more work as I'd want to generalize the operation, cause its window to be automatically updated whenever the target date is changed and allow the resulting spreadsheet to be enlarged as wanted.  Give me a couple of days to work on this and I'll hash something up for you to look at.  

I've also been guessing what might be behind the "Help PDFs" button on your implementation.  If this is a function for displaying cookbooks and manuals, you might think about spawning this as a standalone application which can be launched from NightShift.  This would allow you to evolve it independently as new ideas come to you.  I have a whole gaggle of cookbooks and tricks & tips that I've compiled over the years.  It would be nice to simply dump those into a folder structure to be organized and displayed by a reader app at my whim.  That is, if I've guessed correctly what "Help PDF" is all about.

**Comment by astromiester1** [comment]
No, I just do an auto open of all your pdf doc help files for all the programs you wrote… I think im going to provide a google drive link for the zip file and code if size to big for github… Standbye…

 

Dale

**Comment by astromiester1** [comment]
[Nightshift-master V1.0.0.30.zip](https://github.com/rrskybox/Nightshift/files/15275628/Nightshift-master.V1.0.0.30.zip)

Here ya go...

Thanks
Dale

**Comment by rrskybox** [comment]
Thanks.  I'll take a look at it.

**Comment by rrskybox** [comment]
I completed upgrades to ImagePlanner that support the listing of all targets in a spreadsheet (Build 106).  The format is pretty much the way you had it in your NIghtShift prototype V...30.  Table entries will update if you change selected days or years.  Accordingly, the other ImagePlanner screens will adopt whichever target is selected in the List.  The target altitude data is based on current time of day so that's not particularly useful unless you are reviewing targets immediately before sequencing.  However, if you leave the Altitude window open, then the selection of each individual target will show the altitude graph for that target on the selected date.

With this upgrade to ImagePlanner, I'm going to close this issue.  If you find new issues with Image Planner, please open there.  I'm sure there will be as I probably missed some edge conditions when I was testing this revision.
