### ISSUE TITLE
Nightshift does not have some new attributes in target list.

### ISSUE THREAD

**Issue by astromiester1** [rrskybox/Nightshift#9]
Altitude is very useful and just by hitting refresh button will make it real time. Also, major and minor axis very useful for determining and or verifying FOV . I see you moved it to IP....Sorry....

**Comment by rrskybox** [comment]
I can't argue with what works for you.  That's what it's all about.  What's useful to me is to see the altitude plot over the whole night so I can see whether the target is rising or setting during the shoot, among other things.   I guess the difference is that I set up my imaging schedule during the day -- at a time when the current altitude of a target is not meaningful.  That's why I suggested using the Altitude window on Image Planner.  But, admittedly, it's just a suggestion based on my way of doing things -- one size doesn't fit all.

![image](https://github.com/rrskybox/Nightshift/assets/40242027/0e92723a-bd3e-4e30-b530-6eeeb53d27ce)
